name: sbom-upload

on: push

jobs:
  sbom-upload:
    name: sbom-upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: sbom-upload
        run: |
          CLIENT_ID="445fe771-7406-4b3d-bd78-5bf32da1e8e4"
          SECRET=${{ secrets.RKVST_SECRET }}
          # use curl to obtain a temporary access token for api access using our client id and secret
          RESPONSE=$(curl https://app.rkvst.io/archivist/iam/v1/appidp/token \
              --data-urlencode "grant_type=client_credentials"  \
              --data-urlencode "client_id=${CLIENT_ID}" \
              --data-urlencode "client_secret=${SECRET}")
          echo $RESPONSE
          TOKEN=$(echo -n $RESPONSE | jq -r .access_token)
          echo $TOKEN
          curl -X POST -H "Authorization: Bearer $TOKEN" -F "sbom=@sbom.xml" "https://sbom.rkvst.io/archivist/v1/sboms"
          
